; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:nucleo_g071rb]
platform = https://github.com/mbed-ce/pio-platform-ststm32#dev/add-mbed-ce
board = nucleo_g071rb
framework = mbed-ce
upload_protocol = mbed
monitor_echo = yes
;monitor_speed = 9600
;upload_port = /Volumes/NODE_G071RB
;removing the semicolon above if working on a MAC
